export const emptyCaseDraft = () => ({
    id: null,
    title: "",
    slug: "",
    author: "",
    shortDescription: "",
    introduction: "",
    industry: "",
    tags: [],
    content: [{ heading: "", text: "" }],
    thumbnail_url: "",
    images: [],
    status: "Draft",
    is_published: false,
});